baseurl: '/'
permalink: pretty
title: 'Srushti Ayurvedalaya'

logo:
  mobile: "images/logo/logo.webp"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.webp"
  desktop_height: "32px"
  desktop_width: "64px"

home: 
  limit_services: 3

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  stories:
    output: true
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "ampgallery"
      permalink: /stories/:title/

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-compress-images
  - jekyll-seo-tag
  
compress_images:
  images_path: "images/logo/*.{gif,png,jpg,jpeg,svg}"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

social:
  name: Srushti Ayurvedalaya
  links:
    - https://www.facebook.com/srushtiayurvedalaya
    - https://instagram.com/srushtiayurvedalaya

image:
  path: /images/logo/srushti_og.png
  height: 1080
  weight: 2754
